basePath: /
definitions:
  domain.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  domain.LoginResponse:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastLogin:
        type: string
      lastName:
        type: string
      roles:
        items:
          type: string
        type: array
      username:
        example: admin
        type: string
    type: object
  domain.Role:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  domain.UserCreate:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  domain.UserRead:
    properties:
      createdAt:
        type: string
      email:
        type: string
      failedLoginAttempts:
        type: integer
      firstName:
        type: string
      id:
        type: string
      isDisabled:
        type: boolean
      lastFailedLoginAttempt:
        type: string
      lastLogin:
        type: string
      lastName:
        type: string
      roles:
        items:
          $ref: '#/definitions/domain.Role'
        type: array
      updatedAt:
        type: string
      username:
        type: string
    type: object
  domain.UserUpdate:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
    type: object
  handler.HealthCheckResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Centralized Personal Productivity Application
  title: Mainframe API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user credentials
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.LoginResponse'
      summary: Login user
      tags:
      - Authentication
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: Log out of application
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Logout user
      tags:
      - Authentication
  /api/roles:
    get:
      consumes:
      - application/json
      description: Get all roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Role'
            type: array
      summary: List Roles
      tags:
      - Roles
  /api/users:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.UserRead'
            type: array
      summary: List Users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create a new application user
      parameters:
      - description: New User
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create User
      tags:
      - Users
  /api/users/:id:
    delete:
      consumes:
      - application/json
      description: Delete an application user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete User
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Get one user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UserRead'
      summary: Get User
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update an application user
      parameters:
      - description: Update User
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.UserUpdate'
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Update User
      tags:
      - Users
  /health:
    get:
      consumes:
      - application/json
      description: Perform Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthCheckResponse'
      summary: Health Check
      tags:
      - Health
swagger: "2.0"
